### ISSUE TITLE
Updated driver AIS2IHTR to read temperature register

### ISSUE THREAD

**Issue by lucbeaufils** [STMicroelectronics/st-mems-android-linux-drivers-iio#12]
Hello,

I use an ais2h chip with spi on a project to have accelerometer and temperature sensors. I use a Linux-imx kernel 5.10 in  a Yocto project.
I have no integration problem with the driver but the temperature reading doesn't seem to be implemented.
Do you plan to implement register reading for temperatures on this chip? Or their is a way to have it ?

Thanks

**Comment by mariotesi** [comment]
Hi lucbeaufils,

sorry for the delay in the response. The AIS2IHTR driver (compatible st,ais2ih in st_lis2dw12 driver) has been updated to support the temperature reading.
