### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by peterwoodworth** [STMicroelectronics/st-mems-android-linux-drivers-iio#16]
Hi all,

I can see many of the files in this repo are licensed under GPL v2. However, without mention of this in the README, in a licensing file, or on the page on the [website for this software](https://www.st.com/en/embedded-software/linuxdriveriio.html#tools-software), I don't feel safe treating the entire project as GPL v2. Could you please clearly lay out licensing for this repo and software? Thanks

**Comment by mariotesi** [comment]
It's all code that integrates into the Linux kernel so it is released with GPL v2. The License file and license reference in the README.md file have also been added for completeness.

**Comment by peterwoodworth** [comment]
thanks!
