### ISSUE TITLE
git merge --no-fork-point is unknown option

### ISSUE THREAD

**Issue by MarkusDost** [STMicroelectronics/st-mems-android-linux-drivers-iio#2]
In the README.md it is stated, that the driver code can be merged with the target kernel source with

git merge --no-fork-point linux-5.4.y stmems_iio_github/master

The command git merge doesn't know the option --no-fork-point (https://git-scm.com/docs/git-merge)

**Comment by ciocca-d** [comment]
While most of the git parameters do not change, some does.
The git version you are using (probably) uses the option **--allow-unrelated-histories** for achieving the same.

git merge **--allow-unrelated-histories** linux-5.4.y stmems_iio_github/master
