### ISSUE TITLE
Support of LSM6DSV16X

### ISSUE THREAD

**Issue by jaiwei98** [STMicroelectronics/st-mems-android-linux-drivers-iio#21]
Hi there, is there any plan to support this IMU (LSM6DSV16X) especially the FIFO, Sensor fusion and MLC.

**Comment by mariotesi** [comment]
Hi, LSM6DSV16X is already supported by lsm6dsvx driver ([here](https://github.com/STMicroelectronics/st-mems-android-linux-drivers-iio/blob/master/drivers/iio/stm/imu/st_lsm6dsvx/st_lsm6dsvx_i2c.c#L71) can see the device list)
