### ISSUE TITLE
IIS3DWB vibration sensor support 

### ISSUE THREAD

**Issue by Pankaj-Patil-97** [STMicroelectronics/st-mems-android-linux-drivers-iio#4]
Hello,

I'm using IIS3DWB with ESP32 and planning on using Jetson xavier nx as the next hardware.
Would like to develop and publish the device driver for IIS3DWB.

Would IIS3DHH be a good reference for developing the driver?
https://github.com/STMicroelectronics/st-mems-android-linux-drivers-iio/blob/master/drivers/iio/stm/accel/st_lis3dhh.c

Thank you

**Comment by mariotesi** [comment]
pls refer to [issue17](https://github.com/STMicroelectronics/STMems_Linux_IIO_drivers/issues/17)
