### ISSUE TITLE
How come the max ODR doesn't match that of the datasheet?

### ISSUE THREAD

**Issue by advisoft** [STMicroelectronics/st-mems-android-linux-drivers-iio#9]
https://github.com/STMicroelectronics/st-mems-android-linux-drivers-iio/blob/ad72495db29ebdee00d973f158197e6b8c5d9b2c/drivers/iio/stm/imu/st_ism330dlc/st_ism330dlc_core.c#L242

![image](https://user-images.githubusercontent.com/11500738/233256543-4998ca2c-2d75-4c34-8ab3-18cf557a3d2b.png)

Is it to stop men setting up the drivers and having the interrupts overwhelm the OS?

**Comment by mariotesi** [comment]
We recommend not exceeding the 833 threshold to avoid saturating the OS with interrupts, but if a certain application requires it, anyone can extend support to higher ODRs, in fact these drivers are released under the GPL license and can be modified at will
